build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run

filter:
    excluded_paths:
        - tests/*
        - functions/*
        - themes/*
        - app/*
        - bin/*
        - storage/*
        - public/*
        - vendor/*
    dependency_paths:
        - bootstrap/*
        - config/*

checks:
    php:
        remove_extra_empty_lines: false
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: false
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true

tools:
    external_code_coverage:
        timeout: 600
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [tests, functions, themes, app, bin, storage, public, vendor]
