risky: false
version: 7
preset: psr12
finder:
    exclude:
        - functions
        - themes
        - app
        - bin
        - bootstrap
        - config
        - storage
        - public
        - vendor
        - tests
    name: '*.php'
    not-name:
        - '*.phtml'
