dist: xenial

os:
    - linux

language: php

php:
    - 7.4
    - 8.0

env:
    global:
        - ECHO_MESSAGE="VELOX Test Suite"
        - COMPOSER_FLAGS="--prefer-stable --prefer-dist"

cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/.local

before_script:
    - echo $ECHO_MESSAGE
    - composer self-update
    - composer update $COMPOSER_FLAGS

script:
    - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
