<section class="section is-medium">
    <div class="container">
        <div class="columns">
            <div class="column is-two-thirds">
                <?= View::partial('components/heading', $heading) ?>
                <?= View::partial('components/paragraph', $paragraph) ?>
            </div>
            <div class="column">
                <?= View::partial('components/image', $image) ?>
            </div>
        </div>
    </div>
</section>