{! @extends 'velox/pages/persons/index' !}


{! @block navigationItems !}
    <li><a href="{{ Path::resolveUrl('persons') }}">List</a></li>
{! @endblock !}

{! @block content !}
    <div class="columns is-centered">
        <div class="column is-two-thirds-desktop">
            <h1 class="title">Create a new Person</h1>
            <form action="{{ Path::resolveUrl('persons') }}" method="POST">
                <input type="hidden" name="_method" value="POST">
                {{{ Session::csrf() }}}
                <div class="field">
                    <label class="label">Name</label>
                    <div class="control">
                        <input class="input" type="text" name="name" placeholder="Name" required>
                    </div>
                </div>
                <div class="field">
                    <label class="label">Age</label>
                    <div class="control">
                        <input class="input" type="number" name="age" placeholder="Age" required>
                    </div>
                </div>
                <div class="field">
                    <label class="label">Username</label>
                    <div class="control">
                        <input class="input" type="text" name="username" placeholder="Username">
                    </div>
                </div>
                <div class="field">
                    <label class="label">E-Mail</label>
                    <div class="control">
                        <input class="input" type="text" name="email" placeholder="E-Mail">
                    </div>
                </div>
                <div class="field">
                    <label class="label">Address</label>
                    <div class="control">
                        <input class="input" type="text" name="address" placeholder="Address">
                    </div>
                </div>
                <div class="field">
                    <label class="label">Company</label>
                    <div class="control">
                        <input class="input" type="text" name="company" placeholder="Company">
                    </div>
                </div>
                <hr />
                <div class="field is-grouped">
                    <div class="control">
                        <input class="button is-success" type="submit">
                    </div>
                    <div class="control">
                        <input class="button is-warning is-light" type="reset">
                    </div>
                    <div class="control">
                        <a class="button is-light" href="{{ Path::resolveUrl('persons') }}">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
{! @endblock !}
