<?= Data::set('page.title', $title) ?>

<?= View::partial('hero', [
    'title' => 'Welcome to VELOX',
    'subtitle' => 'The fastest way to build simple websites using PHP!'
]) ?>

<?= View::partial('text', [
    'heading' => [
        'content' => 'Lorem ipsum',
        'class' => 'title',
    ],
    'paragraph' => [
        'content' => 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.',
    ],
]) ?>

<section class="section is-small">
    <div class="container">
        <div class="columns is-centered is-gapless">
            <div class="column is-half">
                <?= View::partial('components/figure', [
                    'src' => Path::resolveUrlFromAssets('images/velox.png'),
                    'alt' => 'VELOX',
                    'class' => 'has-text-centered',
                    'caption' => 'VELOX'
                ]) ?>
            </div>
        </div>
    </div>
</section>

<?= View::partial('message', [
    'title' => 'Lorem ipsum',
    'body' => 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.',
    'class' => 'is-link',
]) ?>
