<?php

/**
 * ---------------------------------------------------------------------------------------------------------------------
 *  This config file contains some global variables that are used by almost all classes (app-wide config).
 * ---------------------------------------------------------------------------------------------------------------------
 */



return [


    // VELOX global directory structure.
    'paths' => [
        'root'      => BASE_PATH,
        'app'       => '{global.paths.root}/app',
        'classes'   => '{global.paths.root}/classes',
        'functions' => '{global.paths.root}/functions',
        'includes'  => '{global.paths.root}/includes',
        'themes'    => '{global.paths.root}/themes',
        'config'    => '{global.paths.root}/config',
        'storage'   => '{global.paths.root}/storage',
        'public'    => '{global.paths.root}/public',
    ],


    // VELOX current environment, [DEV = development, PROD = production].
    'env' => 'DEV',


    // An absolute path or a path from "BASE_PATH" for an HTML file to use for '500 Server Error' responses if an uncaught exception was thrown in production environment.
    'errorPage' => null,


    'logging' => [
        // Whether or not to enable logging of different events of the app. Note that exception will be logged no matter what the value here is.
        'enabled'          => true,
        // The maximum file size of the log file in bytes before it gets truncated.
        'maxFileSize'      => 6.4e+7,
        // The default file name for logs without explicitly given file name on function call.
        'defaultFilename'  => 'autogenerated-' . date('Ymd'),
        // The default writing directory for logs without explicitly given writing directory on function call.
        'defaultDirectory' => '{global.paths.storage}/logs/',
    ],


];
