<div class="content has-text-centered">
    <p>
        <strong>VELOX</strong> by <a href="https://marwanalsoltany.github.io" target="_blank">Marwan Al-Soltany</a>.<br />
        The source code is licensed under <a href="http://opensource.org/licenses/mit-license.php" target="_blank">MIT</a> license.
    </p>
    <p>Check out the project on <a href="https://github.com/MarwanAlsoltany/velox" target="_blank">GitHub</a></p>
    <p>&copy; <?= Data::get('meta.copyrightText', date('Y')) ?></p>
</div>
